pages:
  stage: deploy
  image: mcr.microsoft.com/playwright:focal
  script:
  - npx feed-me-up-scotty
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - main
  retry:
    # Sometimes a website is temporarily slow/down:
    max: 2
    when: always
