[vlive]
title = "BLACKPINK ─ Star Board"
url = "https://www.vlive.tv/channel/F001E5/board/3961"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"
onFail = "stale"

[vlive_notice]
title = "BLACKPINK ─ Notice"
url = "https://www.vlive.tv/channel/F001E5/board/491"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"
onFail = "stale"

[vlive_blink]
title = "BLACKPINK ─ To. BLINK"
url = "https://www.vlive.tv/channel/F001E5/board/724?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"
onFail = "stale"

[vlive_contents]
title = "BLACKPINK ─ Contents"
url = "https://www.vlive.tv/channel/F001E5/board/6826?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"
onFail = "stale"

[tiktok]
title = "BLACKPINK ─ TikTok"
url = "https://www.tiktok.com/@bp_tiktok?"
entrySelector = "div[class='jsx-2261688415 video-feed-item three-column-item']"
titleSelector = "div[class='jsx-2261688415 _ratio_wrapper'] a"
linkSelector = "div a[class='jsx-3808264675 video-feed-item-wrapper']"
imageSelector = "div[class='jsx-828470630 image-card']"
waitUntil = "networkidle"
